// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTHVEL4noin3WKSndSt0a9nCDLZqnrCcE',
    appId: '1:851726073630:web:e2a9e8c6786a550f41530f',
    messagingSenderId: '851726073630',
    projectId: 'ratebridge-2cd72',
    authDomain: 'ratebridge-2cd72.firebaseapp.com',
    storageBucket: 'ratebridge-2cd72.firebasestorage.app',
    measurementId: 'G-NEQTHSWENV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1RGSPu7OY4j0Ux1fXm_fRwQpYQ9vHvnI',
    appId: '1:851726073630:android:ff992af285bb01ec41530f',
    messagingSenderId: '851726073630',
    projectId: 'ratebridge-2cd72',
    storageBucket: 'ratebridge-2cd72.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfUXxPFwSnESQ7L9VLosXYkDaYcEYHq6k',
    appId: '1:851726073630:ios:77a0248fdec85f1b41530f',
    messagingSenderId: '851726073630',
    projectId: 'ratebridge-2cd72',
    storageBucket: 'ratebridge-2cd72.firebasestorage.app',
    iosBundleId: 'com.example.constructionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTHVEL4noin3WKSndSt0a9nCDLZqnrCcE',
    appId: '1:851726073630:web:6ff841767cf5265a41530f',
    messagingSenderId: '851726073630',
    projectId: 'ratebridge-2cd72',
    authDomain: 'ratebridge-2cd72.firebaseapp.com',
    storageBucket: 'ratebridge-2cd72.firebasestorage.app',
    measurementId: 'G-VZ367W6Q7Z',
  );
}
